name: ci

on:
  pull_request:
    brances: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Lookup node version
        run: node --version

      - name: exit
        run: (exit 0)
